# Generated by Django 2.2.5 on 2019-09-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_class', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('s', 'Success'), ('e', 'Failed')], default='P', max_length=1)),
                ('summary', models.CharField(blank=True, max_length=128, null=True)),
                ('scheduled', models.DateTimeField(auto_now=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('job_data_json', models.CharField(blank=True, max_length=4096, null=True)),
                ('result_json', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'ordering': ('-scheduled',),
            },
        ),
    ]
