# Generated by Django 2.2.5 on 2019-09-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobqueues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledjob',
            old_name='job_data_json',
            new_name='input_data_json',
        ),
    ]
